### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by andfy** [NegatioN/VideoLabeler#1]
Hi,
I am trying to use the tool but was wondering about labels format.

Should I define them in a txt-like file (`--label labels.txt` ) 
or 
directly as string in the command line (`--label 'label1, label2'`)?

Thank you.

**Comment by NegatioN** [comment]
@fybonacci As far as i recall, you can just specify a single label for each time-section.
So `--start=5 --stop=10 --label=snow` would label all frames between seconds 5-10 as "Snow", and output one jpg file per second or something. You can output more frames per second by setting `--step=x`

Please feel free to make a PR encoding some way to take in a list of labels and time-encodings, but this could probably also be done by just wrapping it in a bash-script :)

**Comment by andfy** [comment]
Thank you... but I got the following traceback which may come from my install (or not):

![image](https://user-images.githubusercontent.com/46684038/52130081-86ea3c80-2639-11e9-969c-8d7eaf2d45e7.png)

**Comment by NegatioN** [comment]
That looks like a windows cmd-prompt? If so, I don't think I've ever tried running it on Windows, and you're on your own.
Also, regardless, if you run into any problems, I recommend you just try troubleshooting it a bit. You can also run it directly with `python /videolabeler/videolabeler/video_labeler.py` by just changing the local imports. Good luck
